### ISSUE TITLE
W jaki sposób postawić SQL Server i uruchomić skrypt do załadowania przykładowych danych?

### ISSUE THREAD

**Issue by sulmar** [sulmar/vavatech-bsb-dotnet-core-ttd#8]
``` yaml
version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"

```
